### ISSUE TITLE
Weird comments behaviour

### ISSUE THREAD

**Issue by danielbayley** [bsara/language-gitignore#4]
For some reason comments that start with `#*` or `#-` don’t register as a commented line. _Anything_ after `#` should be a comment.

**Comment by bsara** [comment]
Thanks @danielbayley  for letting me know. Sorry that I've taken so long to even acknowledge this issue being posted. I'm hoping to take a look very soon.

**Comment by bsara** [comment]
@danielbayley & @ageoghegan this bug should be fixed and the updates published. I tested it myself, but please make sure it's working for you too.

**Comment by ageoghegan** [comment]
Seems fixed :-)

**Comment by bsara** [comment]
glad to hear it.

**Comment by ageoghegan** [comment]
Actually I found something minor that might be related.  Apparently a double ## changes the syntactical highlighting.  Like this:
![bad_comment](https://cloud.githubusercontent.com/assets/13414546/19397675/bc29bc70-9240-11e6-9d87-713b943cdda8.png)
