### ISSUE TITLE
.npmignore

### ISSUE THREAD

**Issue by kflorence** [bsara/language-gitignore#6]
Can this plugin also support syntax highlighting for `.npmignore`?

**Comment by bsara** [comment]
@kflorence this package is specifically for `.gitignore` files. If I were to support other file types, I would create a separate package to do so.

**Comment by bsara** [comment]
@kflorence you may want to consider checking out this package: https://atom.io/packages/language-dotfiles

**Comment by kflorence** [comment]
`.npmignore` uses the same syntax as `.gitignore`

**Comment by bsara** [comment]
@kflorence I understand that they use the exact same syntax. But given the fact that this package is specifically named for git ignore files, it wouldn't make sense to include other file extensions.

The link I posted in my last comment was the wrong one (sorry), this is the package I meant to post a link to: https://atom.io/packages/language-ignore

I've actually been planning to try and merge this package with the `language-git` package for some time now, but perhaps I'll merge it with `language-ignore` instead. I'm not sure yet.

Thanks so much for the feedback though, I very much appreciate it.
